// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $CpfInput from "./islands/CpfInput.tsx";
import * as $Cursos from "./islands/Cursos.tsx";
import * as $Form from "./islands/Form.tsx";
import * as $Oferta from "./islands/Oferta.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/CpfInput.tsx": $CpfInput,
    "./islands/Cursos.tsx": $Cursos,
    "./islands/Form.tsx": $Form,
    "./islands/Oferta.tsx": $Oferta,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
